const TelegramBot = require('node-telegram-bot-api')
require('dotenv').config()
const token = process.env.TOKEN

const bot = new TelegramBot(token, { polling: true })

const Ужастик_answers = [
  "'Сияние' (The Shining, 1980)",
  "'Изгоняющий дьявола' (The Exorcist, 1973)",
  "'Техасская резня бензопилой' (The Texas Chain Saw Massacre, 1974)",
  "'Полтергейст' (Poltergeist, 1982)",
  "'Пятница, 13-е' (Friday the 13th, 1980)",
  "'Кошмар на улице Вязов' (A Nightmare on Elm Street, 1984)",
  "'Чужой' (Alien, 1979)",
  "Ведьмы из Блэр: Курсовая с того света' (The Blair Witch Project, 1999)",
  "'Звонок' (The Ring, 2002)",
  "'Паранормальное явление' (Paranormal Activity, 2007)",
  "'Заклятие' (The Conjuring, 2013)",
  "'Астрал' (Insidious, 2010)",
  "'Оно' (It, 2017)",
  "'Тихое место' (A Quiet Place, 2018)",
  "'Хэллоуин' (Halloween, 1978)",
  "'Плетеный человек' (The Wicker Man, 1973)",
  "'Суспирия' (Suspiria, 1977)",
  "'Сквозь снег' (Snowpiercer, 2013)",
  "'Детка' (Orphan, 2009)",
  "'Омен'** (The Omen)",
  "'Синистер'** (Sinister)",
  "'Плетеный человек'** (The Wicker Man)",
  "'Нечто'** (The Thing)",
  "'Фантазм'** (Phantasm)",
  "'Восставший из ада'** (Hellraiser)",
  "'Сонная лощина'** (Sleepy Hollow)",
  "'Американская история ужасов'** (American Horror Story)",
  "'Сайлент Хилл'** (Silent Hill)",
  "'Останься со мной'** (Stay)",
  "'28 дней спустя'** (28 Days Later)",
  "'Репортаж'** ([Rec])",
  "'Готика'** (Gothika)",
  "'Мгла'** (The Mist)",
  "'Мученицы'** (Martyrs)",
  "'Добро пожаловать в Zомбилэнд'** (Zombieland)",
  "'Темные небеса'** (Dark Skies)",
  "'Мама'** (Mama)",
  "'Бабадук'** (The Babadook)",
  "'Хижина в лесу'** (The Cabin in the Woods)",
  "'Паранормальное явление 3'** (Paranormal Activity 3)",
  "'Эксперимент'** (The Experiment)",
  "'Кладбище домашних животных'** (Pet Sematary)",
  "'1408'** (1408)",
  "'Зеркала'** (Mirrors)",
  "'Женщина в черном'** (The Woman in Black)",
  "'Оно'** (It)",
  "'Мертвая тишина'** (Dead Silence)",
  "'И гаснет свет...'** (Lights Out)",
  "'Впусти меня'** (Let the Right One In)",
]
const Драма_answers = [
  "'Побег из Шоушенка' (The Shawshank Redemption, 1994)",
  "'Крестный отец' (The Godfather, 1972)",
  "'Форест Гамп' (Forrest Gump, 1994)",
  "'Криминальное чтиво' (Pulp Fiction, 1994)",
  "'Список Шиндлера' (Schindler's List, 1993)",
  "'Гражданин Кейн' (Citizen Kane, 1941)",
  "'Зеленая миля' (The Green Mile, 1999)",
  "'Бойцовский клуб' (Fight Club, 1999)",
  "'12 разгневанных мужчин' (12 Angry Men, 1957)",
  "'Запах женщины' (Scent of a Woman, 1992)",
  "'Семь' (Se7en, 1995)",
  "'Славные парни' (Goodfellas, 1990)",
  "'Крамер против Крамера' (Kramer vs. Kramer, 1979)",
  "'Американская история X' (American History X, 1998)",
  "'Реквием по мечте' (Requiem for a Dream, 2000)",
  "'Милый Билли' (Billy Elliot, 2000)",
  "'Гонка' (Rush, 2013)",
  "'Король говорит!' (The King's Speech, 2010)",
  "'Благие намерения' (Good Will Hunting, 1997)",
  "'Далласский клуб покупателей' (Dallas Buyers Club, 2013)",
  "'Артист'** (The Artist)",
  "'Хатико: Самый верный друг'** (Hachiko: A Dog's Story)",
  "'Шестое чувство'** (The Sixth Sense)",
  "'Славные парни'** (Goodfellas)",
  "'Господин Никто'** (Mr. Nobody)",
  "'Заплати другому'** (Pay It Forward)",
  "'В центре внимания'** (Spotlight)",
  "'Частная жизнь'** (Private Life)",
  "'Адвокат дьявола'** (The Devil's Advocate)",
  "'Тайная жизнь Уолтера Митти'** (The Secret Life of Walter Mitty)",
  "'Даласский клуб покупателей'** (Dallas Buyers Club)", ,
  "'Амели,** (Amélie)",
  "'В поисках счастья'** (The Pursuit of Happyness)",
  "Письма на Иводзиму'** (Letters from Iwo Jima)",
  "Общество мертвых поэтов'** (Dead Poets Society)",
  "Мирный воин'** (Peaceful Warrior)",
  "Шпионский мост'** (Bridge of Spies)",
  "Меня там нет'** (I'm Not There)",
  "Ромовый дневник'** (The Rum Diary)",
  "'Рождение нации'** (The Birth of a Nation)",
  "'Жизнь Эмиля Золя'** (The Life of Emile Zola)",
  "'Унесенные ветром'** (Gone with the Wind)",
  "'Малышка на миллион'** (Million Dollar Baby)",
  "'Ганди'** (Gandhi)",
  "'Могучая Афродита'** (Mighty Aphrodite)",
  "'Модильяни'** (Modigliani)",
  "'Запах женщины''** (Scent of a Woman)",
  "'Год собаки'** (Year of the Dog)",
  "'Музыка сердца'** (Music of the Heart)",
  "'Ешь, молись, люби'** (Eat Pray Love)",
]
const Экшн_answers = [
  "'Крепкий орешек' (Die Hard, 1988)",
  "'Терминатор 2: Судный день' (Terminator 2: Judgment Day, 1991)",
  "'Неудержимые' (The Expendables, 2010)",
  "'Безумный Макс: Дорога ярости' (Mad Max: Fury Road, 2015)",
  "'Скорость' (Speed, 1994)",
  "'Тёмный рыцарь' (The Dark Knight, 2008)",
  "'Матрица' (The Matrix, 1999)",
  "'Гладиатор' (Gladiator, 2000)",
  "'Плохие парни' (Bad Boys, 1995)",
  "'Джон Уик' (John Wick, 2014)",
  "'Ультиматум Борна' (The Bourne Ultimatum, 2007)",
  "'Рейд' (The Raid: Redemption, 2011)",
  "'Леон' (Léon: The Professional, 1994)",
  "'Скала' (The Rock, 1996)",
  "'Коммандо' (Commando, 1985)",
  "'Рэмбо: Первая кровь' (First Blood, 1982)",
  "'Индиана Джонс: В поисках утраченного ковчега' (Raiders of the Lost Ark, 1981)",
  "'Джеймс Бонд: Казино Рояль' (Casino Royale, 2006)",
  "'На гребне волны' (Point Break, 1991)",
  "'Миссия невыполнима: Протокол Фантом' (Mission: Impossible – Ghost Protocol, 2011)",
  "'Ред'** (RED)",
  "'Ультиматум Борна'** (The Bourne Ultimatum)",
  "'Великолепная семёрка'** (The Magnificent Seven)",
  "'Рэмбо: Первая кровь'** (First Blood)",
  "'Топ Ган'** (Top Gun)",
  "'Рыцари севера'** (The 13th Warrior)",
  "'Властелины Вселенной'** (Masters of the Universe)",
  "'Третья мировая'** (World War Z)",
  "'От колыбели до могилы'** (Cradle 2 the Grave)",
  "'Команда А'** (The A-Team)",
  "'Во имя справедливости'** (Under Siege)",
  "'Заложница'** (Taken)",
  "'Идентификация Борна'** (The Bourne Identity)",
  "'Агент 007: Казино Рояль'** (Casino Royale)",
  "'Терминатор'** (The Terminator)",
  "'Судья Дредд'** (Judge Dredd)",
  "'Бэтмен: Начало'** (Batman Begins)",
  "'Прямая угроза'** (Die Hard with a Vengeance)",
  "'Другой мир'** (Underworld)",
  "'Мстители'** (The Avengers)",
  "'Джон Картер'** (John Carter)",
  "'Король Артур'** (King Arthur)",
  "'Хищник'** (Predator)",
  "'Леон'** (Léon: The Professional)",
  "'Изгнанный из ада'** (Shoot 'Em Up)",
  "'Старикам тут не место'** (No Country for Old Men)",
  "'В укромном месте'** (Safe House)",
  "'Ничего не вижу, ничего не слышу'** (See No Evil, Hear No Evil)",
  "'Мальчишник: Ветераны войны'** (War Dogs)",
  "'Каратель'** (The Punisher)",
]
const Комедия_answers = [
  "'Тупой и ещё тупее' (Dumb and Dumber)",
  "'Суперперцы' (Superbad)",
  "'Брюс Всемогущий' (Bruce Almighty)",
  "'Евротур' (EuroTrip)",
  "'Мальчишник в Вегасе' (The Hangover)",
  "'Шрек'(Shrek)",
  "'Американский пирог'** (American Pie)",
  "'Назад в будущее'** (Back to the Future)",
  "'Полицейская академия'** (Police Academy)",
  "'Горячие головы' (Hot Shots!)",
  "'Меня зовут Борис'** (Borat)",
  "'День сурка' (Groundhog Day)",
  "'Медвежонок Паддингтон' (Paddington)",
  "'Такси' (Taxi)",
  "'Стражи Галактики' (Guardians of the Galaxy)",
  "'Реальные упыри' (What We Do in the Shadows)",
  "'Как приручить дракона' (How to Train Your Dragon)",
  "'Маска' (The Mask)",
  "'Один дома' (Home Alone)",
  "'Миссис Даутфайр' (Mrs. Doubtfire)",
  "'Пятьдесят первых поцелуев'** (50 First Dates)",
  "'Как стать принцессой'** (The Princess Diaries)",
  "'Тупой и ещё тупее: Когда Гарри встретил Ллойда'** (Dumb and Dumberer: When Harry Met Lloyd)",
  "'День святого Валентина'** (Valentine's Day)",
  "'Мистер Бин'** (Bean)",
  "'Старски и Хатч'** (Starsky & Hutch)",
  "'Зубная фея'** (Tooth Fairy)",
  "'Реальные упыри'** (What We Do in the Shadows)",
  "'Сестра Джеки'** (Sister Act)",
  "'Без чувств'** (Senseless)",
  "'Как отделаться от парня за 10 дней'** (How to Lose a Guy in 10 Days)",
  "'Парк Юрского периода: Парк'** (Jurassic Park: The Park)",
  "'Пол: Секретный материальчик'** (Paul)",
  "'Солдаты неудачи'** (Tropic Thunder)",
  "'Зубная фея 2'** (Tooth Fairy 2)",
  "'Полицейская академия'** (Police Academy)",
  "'Шпион по соседству'** (The Spy Next Door)",
  "'Большая жратва'** (The Great Buck Howard)",
  "'Гарольд и Кумар уходят в отрыв'** (Harold & Kumar Go to White Castle)",
  "'Голый пистолет 2 1/2: Запах страха'** (The Naked Gun 2 1/2: The Smell of Fear)",
  "'День выборов'** (Election Day)",
  "'Каникулы'** (Vacation)",
  "'Сумасшедшее свидание'** (Date Night)",
  "'Поймай меня, если сможешь'** (Catch Me If You Can)",
  "'Снова ты'** (You Again)",
  "'Маша и Медведь'** (Masha and the Bear)",
  "'Десятидюймовый герой'** (Ten Inch Hero)",
  "'Ограбление по-итальянски'** (The Italian Job)",
  "'Два холостяка на одну свадьбу'** (Wedding Crashers)",
  "'Ёлки'",
]
const Фантастика_aswers = [
  "'Бегущий по лезвию' (Blade Runner)",
  "'Интерстеллар' (Interstellar)",
  "'Матрица' (The Matrix)",
  "'Начало' (Inception)",
  "'Пятый элемент' (The Fifth Element)",
  "'Аватар' (Avatar)",
  "'Звёздные войны: Эпизод IV - Новая надежда' (Star Wars: Episode IV - A New Hope)",
  "'Дюна'(Dune)",
  "'Терминатор 2: Судный день' (Terminator 2: Judgment Day)",
  "'Грань будущего' (Edge of Tomorrow)",
  "'Мстители: Финал' (Avengers: Endgame)",
  "'Эквилибриум' (Equilibrium)",
  "'Контакт' (Contact)",
  "'Гость'(The Host)",
  "'Прометей' (Prometheus)",
  "'Голодные игры' (The Hunger Games)",
  "'12 обезьян' (12 Monkeys)",
  "'Облачный атлас' (Cloud Atlas)",
  "'Гравитация' (Gravity)",
  "'Робокоп' (RoboCop)",
  "'Звездные врата'** (Stargate)",
  "'Игры Эндера'** (Ender's Game)",
  "'Вспомнить все'** (Total Recall)",
  "'Трон'** (TRON)",
  "'Остров'** (The Island)",
  "'Особое мнение'** (Minority Report)",
  "'Искусственный интеллект'** (A.I. Artificial Intelligence)",
  "'Железный человек'** (Iron Man)",
  "'Обитель зла'** (Resident Evil)",
  "'Человек из стали'** (Man of Steel)",
  "'Звездный десант'** (Starship Troopers)",
  "'Луна'** (Moon)",
  "'Время'** (In Time)",
  "'Уравнитель' (Elysium)",
  "'Без лица'** (Face/Off)",
  "'Суррогаты'** (Surrogates)",
  "'Из машины'** (Ex Machina)",
  "'Марсианин'** (The Martian)",
  "'Первому игроку приготовиться'** (Ready Player One)",
  "'Черное зеркало: Брандашмыг'** (Black Mirror: Bandersnatch)",
  "'Люди в черном' ** (Men in Black)",
  "'Вспомнить всё' ** (Total Recall)",
  "'Пассажиры' ** (Passengers)",
  "'Тихоокеанский рубеж' ** (Pacific Rim)",
  "'Дитя человеческое' ** (Children of Men)",
  "'Универсальный солдат' ** (Universal Soldier)",
  "'Хроника' ** (Chronicle)",
  "'Судья Дредд' ** (Dredd)",
  "'Аннигиляция' ** (Annihilation)",
  "'Книга Илая' ** (The Book of Eli)",
]
const Трейлер_answers = [
"'Семь** (Se7en)",
"'Остров проклятых** (Shutter Island)",
"'Психо'** (Psycho)",
"'Тихое место'** (A Quiet Place)",
"'Исчезнувшая'** (Gone Girl)",
"'Немыслимое'** (Unthinkable)",
"'Зодиак'** (Zodiac)",
"'Девушка с татуировкой дракона'** (The Girl with the Dragon Tattoo)",
"'Тревожный вызов'** (The Call)",
"'Молчание ягнят'** (The Silence of the Lambs)",
"'Криминальное чтиво'** (Pulp Fiction)",
"'Идентификация'** (Identity)",
"'Пленницы'** (Prisoners)",
"'Американский психопат'** (American Psycho)",
"'Начало'** (Inception)",
"'Темное наследие'** (Hereditary)",
"'Психо'** (Psycho)",
"'Мы'** (Us)",
"'На игре'** (Nerve)",
"'Чат'** (Chatroom)",
"'Грань будущего** (Edge of Tomorrow)",
"'Законопослушный гражданин'** (Law Abiding Citizen)",
"'Жертва'** (Fallen)",
"'Отступники'** (The Departed)",
"'Девушка в поезде'** (The Girl on the Train)",
"'Исходный код'** (Source Code)",
"'Подозрительные лица'** (The Usual Suspects)",
"'Побочный эффект'** (Side Effects)",
"'Игра'** (The Game)",
"'Шоссе в никуда'** (Lost Highway)",
"'Однажды ночью'** (Once Upon a Time in the Night)",
"'Эффект бабочки'** (The Butterfly Effect)",
"'Прежде чем я усну'** (Before I Go to Sleep)",
"'Области тьм'** (Limitless)",
"'Механик'** (The Mechanic)",
"''Память'** (Rememory)",
"'Не дыши'** (Don't Breathe)",
"'Напролом'** (Lockout)",
"'Десять негритят'** (And Then There Were None)",
"'Враг'** (Enemy)",
"'Миссия невыполнима'** (Mission: Impossible)",
"'Конг: Остров черепа'** (Kong: Skull Island)",
"'Человек на Луне'** (First Man)",
"'Кровавый алмаз'** (Blood Diamond)",
"'Престиж'** (The Prestige)",
"'Двойник'** (The Double)",
"'Машинист'** (The Machinist)",
"'Закон ночи'** (Live by Night)",
"'Петля времени'** (Looper)",
"'До самого конца'** (End of Watch)",
]

const keyboard = [
  ['Ужастик', 'Драма'],
  ['Экшн', 'Комедия'],
  ['Фантастика', 'Трейлер']
]

bot.on('text', (msg) => {
  const chatId = msg.chat.id

  if (msg.text === '/start') {
    bot.sendMessage(chatId, "Бот начинает свою работу", {
      reply_markup: { keyboard }
    })
  } else if (msg.text === '/help') {
    bot.sendMessage(chatId, "выбирать жанры с клавиатуры", {
      reply_markup: { keyboard }
    })
  } else if (msg.text === 'Ужастик') {
    const randomId = Math.floor(Math.random() * Ужастик_answers.length)
    bot.sendMessage(chatId, Ужастик_answers[randomId])
  } else if (msg.text === 'Драма') {
    const randomId = Math.floor(Math.random() * Драма_answers.length)
    bot.sendMessage(chatId, Драма_answers[randomId])
  } else if (msg.text === 'Экшн') {
    const randomId = Math.floor(Math.random() * Экшн_answers.length)
    bot.sendMessage(chatId, Экшн_answers[randomId])
  } else if (msg.text === 'Комедия') {
    const randomId = Math.floor(Math.random() * Комедия_answers.length)
    bot.sendMessage(chatId, Комедия_answers[randomId])
  } else if (msg.text === 'Фантастика') {
    const randomId = Math.floor(Math.random() * Фантастика_aswers.length)
    bot.sendMessage(chatId, Фантастика_aswers[randomId])
  } else if (msg.text === 'Трейлер') {
    const randomId = Math.floor(Math.random() * Трейлер_answers.length)
    bot.sendMessage(chatId, Трейлер_answers[randomId])
  }
})